### ISSUE TITLE
dist files not running on nginx, debian 11

### ISSUE THREAD

**Issue by isemann** [isemann/RPX-100-WEB#2]
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "applictaion/javascript". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by isemann** [comment]
resloved, by removing (manulay) the type="module" entry in index.html
<script src="runtime.e4371da096983ebf.js"></script><script src="polyfills.37f79b4f5eb38b04.js"></script><script src="main.5eafadac8135f97c.js"></script>

**Comment by fabianfrz** [comment]
the module is likely correct where it was - the problem is that application/javascript is not a valid content-type anymore.  It should likely be text/javascript which needs to be configured in mime.types in nginx. Maybe that is different between ubuntu's version and debian's.

See: https://www.rfc-editor.org/rfc/rfc9239

**Comment by isemann** [comment]
true. interessting reading, seems this part is effecing the scripts: Deprecated alias names for this type...
